#!/usr/bin/env bash
# Aircrack-ng/crack

# crack
#   Crack demo*.cap file using aircrack

set -euo pipefail
# -e exit if any command returns non-zero status code
# -u prevent using undefined variables
# -o pipefail force pipelines to fail on first non-zero status code

IFS=$'\n\t'
# Set Internal Field Separator to newlines and tabs
# This makes bash consider newlines and tabs as separating words
# See: http://redsymbol.net/articles/unofficial-bash-strict-mode/


function usage {
  echo -e "\\n  ./crack [network-bssid] \\n"
  echo "  Ceack demo*.cap using aircrack-ng "

  exit 0
}


function ctrl_c {
  echo -e "\\n[ ] ${USER} has chosen to quit!"
  exit 1
}


function main {

  declare -r bssid=${1:-""}

  if [[ $# -eq 0 ]] ; then
    # If no args then print help
    usage
  elif ! [[ "${bssid}" =~ ^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$ ]]; then
    echo "[ ] network-bssid is not a valid MAC address!"
    exit 1
  fi

  trap ctrl_c SIGINT
  # Detect and react to the user hitting CTRL + C

  aircrack-ng -w wordz.lst -b "${bssid}" demo*.cap
}

main "$@"
